### ISSUE TITLE
java.lang.NoSuchFieldError: YELLOW

### ISSUE THREAD

**Issue by intagaming** [NukkitRu/DbLib#2]
If i load my plugin with DbLib 0.1.0 as Library and load the DbExample plugin using DbLib 0.1.1 and load DbLib 0.1.0 or 0.1.1 as a Plugin, my plugin's MySQL loading will work. But if i disable DbExample, the loading on my plugin won't work. If i change the DbExample DbLib's Library version to 0.1.0, the loading won't work either. In conclusion, i need to load DbLib 0.1.0 and 0.1.1 as Library and load the DbLib plugin either to get my code below works.
Code:

```
Connection connect = DbLib.getMySqlConnection(
                (String) mysql.get("host"),
                (Integer) mysql.get("port"),
                (String) mysql.get("database"),
                (String) mysql.get("user"),
                (String) mysql.get("password")
        );
```

Also if i don't use the dual-library like that, this warning will come:

```
> Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The dri
ver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
```

**Comment by fromgate** [comment]
Hello,
 this message
/> Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is`com.mysql.cj.jdbc.Driver'. The dri
ver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary."

Is come from MySQL and it shown because ORMLite included in DBLib using old method to init MySQL driver. 
You can ignore it; it affects nothing.

And you must use only one DBLib - 0.1.1,
but don't forget to define it as dependency in your plugin.yml.

**Comment by intagaming** [comment]
@fromgate 
Yes i've depended that:
`depend: [DbLib]`
But my code just return null..

```
Connection connect = DbLib.getMySqlConnection(
                (String) mysql.get("host"),
                (Integer) mysql.get("port"),
                (String) mysql.get("database"),
                (String) mysql.get("user"),
                (String) mysql.get("password")
        );

        if (connect == null) {
            getLogger().error("Can't connect to MySQL Database.");
            getServer().getPluginManager().disablePlugin(this);
            return;
        }
```

The MySQL data is correct:
![image](https://cloud.githubusercontent.com/assets/16471365/17670681/6601f7ae-633d-11e6-94ff-66f5ab37951d.png)

**Comment by intagaming** [comment]
I guess i've solved my old problem. The new problem is:

```
> Exception in thread "main" java.lang.NoSuchFieldError: YELLOW
        at ru.nukkit.dblib.DbLibPlugin.onEnable(DbLibPlugin.java:32)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:456)
        at cn.nukkit.Server.enablePlugin(Server.java:618)
        at cn.nukkit.Server.enablePlugins(Server.java:607)
        at cn.nukkit.Server.<init>(Server.java:454)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

This will just happen with DbLib 0.1.1 release, not source code.

**Comment by fromgate** [comment]
Hmm.. Oh! Yeah! TextFormat was chnaged...
Just a moment, I will upload compatible version

**Comment by fromgate** [comment]
https://github.com/NukkitRu/DbLib/releases/tag/v0.1.2
